---
# Playbook to execute Ansible tests for docker role.
- name: Verify
  hosts: all
  gather_facts: true
  collections:
    - community.docker
  vars:
    verify_docker_compose: true
    docker_compose_app_path: ~/webapp
    debug: false
  tasks:
    - name: Verify OS distribution is 'Debian'
      assert:
        that: ansible_os_family == 'Debian'
        fail_msg: "OS distribution must be 'Debian' to use with Raspberry Pi"
        success_msg: "OS distribution matches requirements of Raspberry Pi"
    # - name: Create a Hello-world container
    #   community.docker.docker_container:
    #     name: helloworld
    #     image: hello-world
    # - name: Stop a container
    #   community.docker.docker_container:
    #     name: helloworld
    #     state: stopped
    # - name: Remove container
    #   community.docker.docker_container:
    #     name: helloworld
    #     state: absent
    - name: Verify Docker
      import_tasks: tests/verify_docker.yml

    - name: Verify Docker Compose
      import_tasks: tests/verify_docker_compose.yml
      when: verify_docker_compose
