---
# tasks file for checkwifi
- name: Copy checkwifi script to server
  become: yes
  template:
    src: checkwifi.sh.j2
    dest: /usr/local/bin/checkwifi.sh
    mode: 755

- name: Schedule cronjob to run the network service restart script
  cron:
    name: "Check Wifi status"
    minute: "*/5"
    job: "/usr/bin/sudo -H /usr/local/bin/checkwifi.sh >> /dev/null 2>&1"